[package]
name = "web_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.1.1", features = ["llvm14-0"] }
rust_compiler = { version = "0.1.0", path = "../rust_compiler"}
rocket = { version ="=0.5.0-rc.3", features = ["json"] }